#!/bin/bash

echo ""
echo "Please disconnect and ARDUINO"
echo ""

sudo usermod -a -G dialout $USER


sudo cp `rospack find busbot_systems`/48-arduino.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart

echo "Now reconect"
